name: Deploy
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    name: A job to deploy blog.
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: true # Checkout private submodules(themes or something else).
      - name: Install npm denpendency & Hexo Deploy
        run: |
          echo "${{ secrets.ID_RSA }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan -t rsa posts.hufeifei.cn >> ~/.ssh/known_hosts
          git config --global user.email "hff1996723@gmail.com"
          git config --global user.name "github/holmofy"
          npm install -g hexo-cli && npm install
          hexo clean && hexo g && hexo d